# Generated by Django 3.2.4 on 2021-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210629_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(default='pass0513', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, default='pass0513', max_length=100),
            preserve_default=False,
        ),
    ]
